### ISSUE TITLE
155 mm ArtilleryTurret Shells Not Colliding

### ISSUE THREAD

**Issue by TheRightArm** [SpannerMonkey/SM_Armory#1]
It took me a little time but I finally got this mod up and running today.  I'm working my way through all of the guns in this and the AFV pack trying them out and trying to decide which one I want to equip my current MBT with.  The first turret I tried was the 155 mm ArtilleryTurret.  I fired multiple shots at various gas tanks and buildings around the KSC, trying to get a feel for how the gun handled, and I quickly noticed a large lack of explosions.  I thought I had done something wrong with the install, but a quick run through some of the other guns included in the packs indicated that this particular turret's shells just are not colliding properly, as all of the other turrets I have tried out thus far have worked perfectly.  To test these turrets i have been loading them in on my tank on the runway, selecting them in BDA, and firing at the fuel tank cluster next to the SPH.  If the shells collide as intended, the fuel tanks will blow up for most tank caliber guns and spark the shots for smaller weapons.  There is no explosion when testing this turret on my build and the shell appears to pass clean through.

**Comment by TheRightArm** [comment]
Still testing turrets, the T-90 turret and the Leo 2 turret are also giving me this issue.  The rest seem to be working as intended.

**Comment by SpannerMonkey** [comment]
Thank you for the report . This behavior has been seen previously although I thought it had been rectified. Will address immediately

**Comment by TheRightArm** [comment]
I did indeed have CAL installed.  The link you provided wouldn't work for me but I did go check the CAL forum page and update from there.  Testing with updated CAL still has shells from the 3 turrets in question phasing through buildings and pretty much everything else.  Anything else I can try on my end to try and save you some trouble?

**Comment by SpannerMonkey** [comment]
I know what the trouble is . I developed AFV's as the same time as doing BDA dev work which involved armor penetration and bullet types and some of the turrets picked up the dev work,  that being bullet type definitions in the cfg .  As an insta fix you could try 1 of two things in the relevant cfg find and comment out
`	bulletType = 122mmBullet///  it will be caliber related for all , this from the Leo`

Or paste the below into CAL as it contains the dev info needed

[https://www.dropbox.com/s/54v603kbfo4a6c7/BulletDefs.zip?dl=0](url)

I will very shortly (next AM)  an update that contains the dev values,  apologies for the inconvenience, and thanks again for the report

**Comment by TheRightArm** [comment]
It's all good, glad you were able to figure it out.  I'll try patching in the bullet defs into CAL when I have a chance and I'll DL the update once you put it out.  I've been enjoying your work thoroughly, top notch as usual. :)

**Comment by SpannerMonkey** [comment]
Believe this fixed as no further reports of phantom shells have been made,  please let me know if it's still an issue
