### ISSUE TITLE
Texture switching for Flak 88 and AFV Tank parts isn't working

### ISSUE THREAD

**Issue by MuricanJeb** [SpannerMonkey/SM_Armory#4]
KSP.log is below. I had to change it into a .txt file to upload it here.

[KSP.txt](https://github.com/SpannerMonkey/SM_Armory/files/1151297/KSP.txt)

**Comment by SpannerMonkey** [comment]
Thanks for your report/s please separate issues when reporting bugs and keep reports specific to the mod concerned , Please remember I have over 1000 parts to manage.
Causes identified will be fixed as part of next update

**Comment by MuricanJeb** [comment]
Alirght, thanks man.
I'll try to organize my bug reports later on.

**Comment by SpannerMonkey** [comment]
Checked sorted and working in next release, both AFV and 88 switch
Cheers
